version: '3'

services:
  web:
    build: .
    command: >
      /bin/bash -c "
        sleep 5;
        python3 manage.py runserver 0.0.0.0:8090;
      "
    volumes:
      - .:/code
    ports:
      - "8090:8090"
    links:
      - postgres:postgres
      - redis:redis
    depends_on:
      - "postgres"
#    command: ["./wait-for-it.sh", "postgres:5432", "--", "python3", "manage.py", "runserver", "0.0.0.0:8090"]

  postgres:
    image: postgres:latest
    expose:
      - "5432"

  redis:
    image: redis:latest
    expose:
      - "6379"
