version: '3'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
      - redis:redis

  postgres:
    image: postgres:latest
    expose:
      - "5432"

  redis:
    image: redis:latest
    expose:
      - "6379"
